##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## repository Makefile
## EXAMPLE DE MAKEFILE POUR COMPILER UNE LIBRAIRIE
##

NAME	=	libmy_sharedgames

G1	=	nibbler/

G2	=	pacman/

LIBSHAREDNAME	=	$(NAME).so

COMPLIB	=	ar rc

all:	$(LIBSHAREDNAME)

$(LIBSHAREDNAME):

clean:

fclean:	clean

re:	fclean all

.PHONY:	clean fclean re
